# Generated by Django 3.2.3 on 2021-05-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('image1', models.ImageField(upload_to="'static/img'", verbose_name='Изображение1')),
                ('image2', models.ImageField(upload_to="'static/img'", verbose_name='Изображение2')),
                ('image3', models.ImageField(upload_to="'static/img'", verbose_name='Изображение3')),
                ('article', models.CharField(max_length=20, verbose_name='Артикул')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Вечернее платье',
                'verbose_name_plural': 'Вечерние платья',
            },
        ),
    ]
