# Generated by Django 3.2.3 on 2021-05-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_evening'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('image1', models.ImageField(upload_to="'static/img'", verbose_name='Изображение1')),
                ('article', models.CharField(max_length=20, verbose_name='Артикул')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('type', models.IntegerField(verbose_name='Тип аксессуара')),
            ],
            options={
                'verbose_name': 'Аксессуар',
                'verbose_name_plural': 'Аксессуары',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('image1', models.ImageField(upload_to='img/', verbose_name='Изображение1')),
                ('image2', models.ImageField(upload_to='img/', verbose_name='Изображение2')),
                ('image3', models.ImageField(upload_to='img/', verbose_name='Изображение3')),
                ('notes', models.TextField(verbose_name='Метки')),
                ('article', models.CharField(max_length=20, verbose_name='Артикул')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('priceSale', models.IntegerField(verbose_name='Цена со скидкой')),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('image1', models.ImageField(upload_to="'static/img'", verbose_name='Изображение1')),
                ('article', models.CharField(max_length=20, verbose_name='Артикул')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('type', models.IntegerField(verbose_name='Тип обуви')),
            ],
            options={
                'verbose_name': 'Обувь',
                'verbose_name_plural': 'Обувь',
            },
        ),
        migrations.CreateModel(
            name='Veil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('image1', models.ImageField(upload_to="'static/img'", verbose_name='Изображение1')),
                ('article', models.CharField(max_length=20, verbose_name='Артикул')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('type', models.IntegerField(verbose_name='Тип фаты')),
            ],
            options={
                'verbose_name': 'Фата',
                'verbose_name_plural': 'Фата',
            },
        ),
    ]
