# Generated by Django 3.2.3 on 2021-05-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_accessories_sale_shoes_veil'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveningDress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('image1', models.ImageField(upload_to="'static/img'", verbose_name='Изображение1')),
                ('image2', models.ImageField(upload_to="'static/img'", verbose_name='Изображение2')),
                ('image3', models.ImageField(upload_to="'static/img'", verbose_name='Изображение3')),
                ('article', models.CharField(max_length=20, verbose_name='Артикул')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('type', models.IntegerField(verbose_name='Тип платья')),
                ('color', models.IntegerField(verbose_name='Цвет платья')),
            ],
            options={
                'verbose_name': 'Вечернее платье 2',
                'verbose_name_plural': 'Вечерние платья 2',
            },
        ),
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('image1', models.ImageField(upload_to='img/', verbose_name='Изображение1')),
                ('image2', models.ImageField(upload_to='img/', verbose_name='Изображение2')),
                ('image3', models.ImageField(upload_to='img/', verbose_name='Изображение3')),
                ('notes', models.TextField(verbose_name='Метки')),
                ('article', models.CharField(max_length=20, verbose_name='Артикул')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('priceSale', models.IntegerField(verbose_name='Цена')),
                ('type', models.IntegerField(verbose_name='Тип платья')),
                ('color', models.IntegerField(verbose_name='Цвет платья')),
            ],
            options={
                'verbose_name': 'Свадебное платье 2',
                'verbose_name_plural': 'Свадебные платья 2',
            },
        ),
        migrations.AlterModelOptions(
            name='positions',
            options={'verbose_name': 'Свадебное платье', 'verbose_name_plural': 'Свадебные платья'},
        ),
    ]
